version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-task2
    ports:
      - '5031:5432'
    environment:
      POSTGRES_DB: hr_task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: Backend-task2
    ports:
      - '3064:3064'
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin123
      PGDATABASE: hr_task_management
      PGHOST: postgres
      PGPORT: 5432

  frontend:
    build:
      context: ./Frontend
    container_name: Frontend-task2
    ports:
      - '8091:80'

  hr:
    build:
      context: ./HR
    container_name: HR-task2
    ports:
      - '8092:80'

volumes:
  postgres_data:


